name: ci
  
on: [push, workflow_dispatch]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v2
    - name: Unit tests
      shell: pwsh
      run: ./test/run.ps1
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: testresult.xml
  
  test-action-minimal-dev:
    needs: unit-test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    environment: Dev
    steps:
    - uses: actions/checkout@v2

    - name: Set environment specific variables
      uses: jnus/json-variables@main
      with:
        scope: Dev
        configFile: 'variables.minimal.json'
        secrets: '${{ toJson(secrets) }}'
    
    - name: Assert
      shell: pwsh
      run: |
        $here = Split-Path $MyInvocation.MyCommand.Definition
        $path = Join-Path -Path ./ -ChildPath 'test'
        $module = Join-Path -Path $path -ChildPath 'Assertion.psm1'
        Import-Module $module -Force
        Assert-EnvVar -actual ${{env.Url}} -expected 'https://someDevHostName.com' -envVar "env.Url"
        Assert-EnvVar -actual ${{env.HostName}} -expected 'someDevHostName' -envVar "env.HostName"
  
  test-action-minimal-devtest:
    needs: unit-test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    environment: DevTest
    steps:
    - uses: actions/checkout@v2

    - name: Set environment specific variables
      uses: jnus/json-variables@main
      with:
        scope: DevTest
        configFile: 'test/variables.minimal.json'
        secrets: '${{ toJson(secrets) }}'   

    - name: Assert
      shell: pwsh
      run: |
        $here = Split-Path $MyInvocation.MyCommand.Definition
        $path = Join-Path -Path ./ -ChildPath 'test'
        $module = Join-Path -Path $path -ChildPath 'Assertion.psm1'
        Import-Module $module -Force
        Assert-EnvVar -actual '${{env.Url}}' -expected 'https://someDevTestHostName.com' -envVar "env.Url"
        Assert-EnvVar -actual '${{env.HostName}}' -expected 'someDevTestHostName' -envVar "env.HostName"
        Assert-EnvVar -actual '${{env.SecretA}}' -expected 'repo_secret_a' -envVar "env.SecretA"
        Assert-EnvVar -actual '${{env.ConnectionString}}' -expected 'username=user;password=repo_secret_a' -envVar "env.ConnectionString"
  
